SNAKE_BOARD_CONFIG = {
    'grid_size': 20,
    'cell_size': 30,
    'initial_snake_length': 3,
    'bonus_healthy_items': 1,
    'max_harmful_items': 2,
    'chemical_effect_seconds': 5,
}


SNAKE_FOOD_ITEMS = [
    {
        'code': 'chicken',
        'label': 'Кусок курицы',
        'emoji': '🍗',
        'kind': 'healthy',
        'macro': 'protein',
        'calories': 60,
        'protein': 15.0,
        'fat': 0.0,
        'carb': 0.0,
        'color': '#d96f32',
        'description': 'Полезный белок для роста и силы.',
    },
    {
        'code': 'butter',
        'label': 'Кусочек масла',
        'emoji': '🧈',
        'kind': 'healthy',
        'macro': 'fat',
        'calories': 50,
        'protein': 0.0,
        'fat': 5.6,
        'carb': 0.0,
        'color': '#f4c542',
        'description': 'Даёт жиры и повышает калорийность рациона.',
    },
    {
        'code': 'bread',
        'label': 'Ломтик хлеба',
        'emoji': '🍞',
        'kind': 'healthy',
        'macro': 'carb',
        'calories': 70,
        'protein': 0.0,
        'fat': 0.0,
        'carb': 17.5,
        'color': '#c68642',
        'description': 'Источник углеводов и энергии.',
    },
    {
        'code': 'burger',
        'label': 'Бургер',
        'emoji': '🍔',
        'kind': 'harmful',
        'macro': 'mixed',
        'calories': 210,
        'protein': 10.0,
        'fat': 10.0,
        'carb': 20.0,
        'color': '#c84c35',
        'description': 'Резко поднимает калории и сбивает баланс БЖУ.',
    },
    {
        'code': 'chemistry',
        'label': 'Колба с химией',
        'emoji': '🧪',
        'kind': 'hazard',
        'macro': 'none',
        'calories': 0,
        'protein': 0.0,
        'fat': 0.0,
        'carb': 0.0,
        'color': '#4ea3ff',
        'description': 'На 5 секунд змейка теряет управление и двигается случайно.',
    },
]


LOSE_REASON_LABELS = {
    'wall_collision': 'Столкновение со стеной',
    'self_collision': 'Столкновение с собой',
    'chemical_wall_collision': 'Столкновение со стеной во время действия колбы',
    'chemical_self_collision': 'Столкновение с собой во время действия колбы',
    'not_enough_calories': 'Не хватило калорий до конца времени',
    'macro_balance_failed': 'Баланс БЖУ вышел за допустимые пределы',
    'calorie_overflow': 'Превышен допустимый лимит калорий',
}
