# Generated by Django 5.2.1 on 2025-05-12 15:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('calories_per_100g', models.FloatField()),
                ('protein_per_100g', models.FloatField()),
                ('fat_per_100g', models.FloatField()),
                ('carbohydrate_per_100g', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_grams', models.FloatField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooddiary.food')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('birth_date', models.DateField(default=datetime.date(1990, 1, 1))),
                ('height_cm', models.IntegerField(default=170)),
                ('weight_kg', models.FloatField(default=70.0)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Сидячий'), ('light', 'Легкая активность'), ('moderate', 'Умеренная активность'), ('active', 'Высокая активность')], default='sedentary', max_length=20)),
                ('goal', models.CharField(choices=[('lose', 'Снижение веса'), ('maintain', 'Поддержание веса'), ('gain', 'Набор массы')], default='maintain', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
