# Generated by Django 5.2.1 on 2026-02-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caloriecounterquestion',
            name='option4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caloriecounterquestion',
            name='option5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
