# Generated by assistant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_caloriecounterquestion_option4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergameresult',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], max_length=10, null=True),
        ),
    ]
