# Generated by Codex on 2026-03-25

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_snake_levels(apps, schema_editor):
    SnakeGameLevel = apps.get_model('games', 'SnakeGameLevel')

    levels = [
        {
            'code': 'snake-breakfast',
            'title': 'Завтрак',
            'difficulty': 'easy',
            'meal_type': 'breakfast',
            'sort_order': 1,
            'target_calories': 600,
            'min_calories': 580,
            'max_calories': 620,
            'target_protein_percent': 30,
            'min_protein_percent': 25,
            'max_protein_percent': 35,
            'target_fat_percent': 25,
            'min_fat_percent': 20,
            'max_fat_percent': 30,
            'target_carb_percent': 45,
            'min_carb_percent': 40,
            'max_carb_percent': 50,
            'time_limit_seconds': 120,
            'initial_speed': Decimal('5.50'),
            'speed_step': Decimal('2.80'),
            'is_active': True,
        },
        {
            'code': 'snake-lunch',
            'title': 'Обед',
            'difficulty': 'hard',
            'meal_type': 'lunch',
            'sort_order': 2,
            'target_calories': 900,
            'min_calories': 880,
            'max_calories': 920,
            'target_protein_percent': 30,
            'min_protein_percent': 25,
            'max_protein_percent': 35,
            'target_fat_percent': 30,
            'min_fat_percent': 25,
            'max_fat_percent': 35,
            'target_carb_percent': 40,
            'min_carb_percent': 35,
            'max_carb_percent': 45,
            'time_limit_seconds': 180,
            'initial_speed': Decimal('6.00'),
            'speed_step': Decimal('4.50'),
            'is_active': True,
        },
        {
            'code': 'snake-dinner',
            'title': 'Ужин',
            'difficulty': 'medium',
            'meal_type': 'dinner',
            'sort_order': 3,
            'target_calories': 600,
            'min_calories': 580,
            'max_calories': 620,
            'target_protein_percent': 40,
            'min_protein_percent': 35,
            'max_protein_percent': 45,
            'target_fat_percent': 30,
            'min_fat_percent': 25,
            'max_fat_percent': 35,
            'target_carb_percent': 30,
            'min_carb_percent': 25,
            'max_carb_percent': 35,
            'time_limit_seconds': 90,
            'initial_speed': Decimal('6.20'),
            'speed_step': Decimal('3.20'),
            'is_active': True,
        },
    ]

    for level_data in levels:
        SnakeGameLevel.objects.update_or_create(
            code=level_data['code'],
            defaults=level_data,
        )


def unseed_snake_levels(apps, schema_editor):
    SnakeGameLevel = apps.get_model('games', 'SnakeGameLevel')
    SnakeGameLevel.objects.filter(
        code__in=['snake-breakfast', 'snake-lunch', 'snake-dinner']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_add_difficulty_to_usergameresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeGameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкая'), ('medium', 'Средняя'), ('hard', 'Сложная')], max_length=10)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('target_calories', models.PositiveIntegerField()),
                ('min_calories', models.PositiveIntegerField()),
                ('max_calories', models.PositiveIntegerField()),
                ('target_protein_percent', models.PositiveSmallIntegerField()),
                ('min_protein_percent', models.PositiveSmallIntegerField()),
                ('max_protein_percent', models.PositiveSmallIntegerField()),
                ('target_fat_percent', models.PositiveSmallIntegerField()),
                ('min_fat_percent', models.PositiveSmallIntegerField()),
                ('max_fat_percent', models.PositiveSmallIntegerField()),
                ('target_carb_percent', models.PositiveSmallIntegerField()),
                ('min_carb_percent', models.PositiveSmallIntegerField()),
                ('max_carb_percent', models.PositiveSmallIntegerField()),
                ('time_limit_seconds', models.PositiveIntegerField()),
                ('initial_speed', models.DecimalField(decimal_places=2, default=6.0, max_digits=4)),
                ('speed_step', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game_level',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SnakeGameUserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('total_wins', models.PositiveIntegerField(default=0)),
                ('best_result_level_1', models.PositiveIntegerField(default=0)),
                ('best_result_level_2', models.PositiveIntegerField(default=0)),
                ('best_result_level_3', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snake_game_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snake_game_user_stats',
            },
        ),
        migrations.CreateModel(
            name='SnakeGameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('is_win', models.BooleanField(default=False)),
                ('lose_reason', models.CharField(blank=True, choices=[('wall_collision', 'Столкновение со стеной'), ('self_collision', 'Столкновение с собой'), ('chemical_wall_collision', 'Столкновение со стеной во время действия колбы'), ('chemical_self_collision', 'Столкновение с собой во время действия колбы'), ('not_enough_calories', 'Не хватило калорий'), ('macro_balance_failed', 'Нарушен баланс БЖУ'), ('calorie_overflow', 'Превышены калории')], max_length=32)),
                ('total_calories', models.PositiveIntegerField(default=0)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_fat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_carb', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('protein_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carb_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.snakegamelevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snake_game_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snake_game_session',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.RunPython(seed_snake_levels, unseed_snake_levels),
    ]
