# Generated by Django 5.2.1 on 2026-03-26 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_snake_game_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitaminGameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('time_limit_seconds', models.PositiveIntegerField(default=60)),
                ('start_value', models.PositiveSmallIntegerField(default=55)),
                ('normal_min_value', models.PositiveSmallIntegerField(default=40)),
                ('normal_max_value', models.PositiveSmallIntegerField(default=70)),
                ('min_critical_value', models.PositiveSmallIntegerField(default=20)),
                ('max_critical_value', models.PositiveSmallIntegerField(default=90)),
                ('drain_per_second', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vitamin_game_level',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VitaminGameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('is_win', models.BooleanField(default=False)),
                ('lose_reason', models.CharField(blank=True, choices=[('vitamin_a_low', 'Авитаминоз: витамин A'), ('vitamin_c_low', 'Авитаминоз: витамин C'), ('vitamin_d_low', 'Авитаминоз: витамин D'), ('vitamin_a_high', 'Гипервитаминоз: витамин A'), ('vitamin_c_high', 'Гипервитаминоз: витамин C'), ('vitamin_d_high', 'Гипервитаминоз: витамин D')], max_length=32)),
                ('vitamin_a', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vitamin_c', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vitamin_d', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitamin_game_attempts', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.vitamingamelevel')),
            ],
            options={
                'db_table': 'vitamin_game_attempt',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
