# Generated by Django 5.2.1 on 2026-04-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_vitamingamelevel_vitamingameattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitamingameattempt',
            name='selected_vitamins',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vitamingameattempt',
            name='vitamin_b',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vitamingameattempt',
            name='vitamin_e',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vitamingameattempt',
            name='vitamin_k',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vitamingameattempt',
            name='lose_reason',
            field=models.CharField(blank=True, choices=[('vitamin_a_low', 'Авитаминоз: витамин A'), ('vitamin_c_low', 'Авитаминоз: витамин C'), ('vitamin_d_low', 'Авитаминоз: витамин D'), ('vitamin_e_low', 'Авитаминоз: витамин E'), ('vitamin_k_low', 'Авитаминоз: витамин K'), ('vitamin_b_low', 'Авитаминоз: витамин B'), ('vitamin_a_high', 'Гипервитаминоз: витамин A'), ('vitamin_c_high', 'Гипервитаминоз: витамин C'), ('vitamin_d_high', 'Гипервитаминоз: витамин D'), ('vitamin_e_high', 'Гипервитаминоз: витамин E'), ('vitamin_k_high', 'Гипервитаминоз: витамин K'), ('vitamin_b_high', 'Гипервитаминоз: витамин B')], max_length=32),
        ),
    ]
